### ISSUE TITLE
Issue for bitsandbytes /// NameError: name 'cuda_setup' is not defined. Did you mean: 'CUDASetup'?

### ISSUE THREAD

**Issue by kskim-phd** [tloen/llama-int8#15]
Hi, thanks for sharing the wonderful code.
But I got the following error so could you clarify how to solve it? 
I think it is better if you can clarify how to install bitsandbytes with version (e.g., https://pypi.org/project/bitsandbytes-cuda113/) in requirements.txt 

Thank you!!

===========================================================

$MYPATH/python3.10/site-packages/bitsandbytes/cuda_setup/main.py", line 153, in is_cublasLt_compatible
    cuda_setup.add_log_entry("WARNING: Compute capability < 7.5 detected! Only slow 8-bit matmul is supported for your GPU!", is_warning=True)

NameError: name 'cuda_setup' is not defined. Did you mean: 'CUDASetup'?

**Comment by tloen** [comment]
See https://github.com/TimDettmers/bitsandbytes/pull/115/files
